// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwzwawdonnzishjeuity.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3endhd2Rvbm56aXNoamV1aXR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyMDAxODMsImV4cCI6MjA1Mjc3NjE4M30.a5w8qy4wlm-osk_oErumZDkdM8wkn7UuoTvrstZKkVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);